### ISSUE TITLE
Add No Position option next to Vote to allow comments & display as third column

### ISSUE THREAD

**Issue by dallasjc** [voteliquid/liquid.us#74]
Selecting No Position would allow you to comment and debate on a bill without voting or declining to vote. This way, you're still represented by your proxy and you don't have to cast a vote (and represent others) in an area you're uncertain in in order to participate in debate. 

As is, if you want to participate you have to abstain or take a position in an area where you might be an expert in.

Displaying them prominently as a third column as also a big opportunity to clearly identify what areas people are uncertain about.

We could also change it so that when members of Congress abstain, it's treated as No Position.

**Comment by dsernst** [comment]
Abstain's now visible
